package Model;

enum Params {
    A,
    AF,
    B,
    C,
    INDEXED_C, // ($0xFFF0 + C)
    BC,
    D,
    E,
    DE,
    H,
    L,
    HL,
    NN,   //  immediate absolute address 2byte
    N,    //  immediate value 1byte
    INDEXED_N, // N(1 byte) + 0xFF00
    SP,   //  stack pointer
    INDEXED_SP,
    BIT0,
    BIT1,
    BIT2,
    BIT3,
    BIT4,
    BIT5,
    BIT6,
    BIT7,
    PC,
    CC_NZ, // condition flag argument
    CC_Z,
    CC_NC,
    CC_C,
    NONE;

    private int immediateVal;
    public void setImmediateVal(int immediateVal) {
        this.immediateVal = (this == Params.INDEXED_N) ? 0xFF00 + immediateVal : immediateVal;
    }

    public int getImmediateVal() { return this.immediateVal; }

    @Override
    public String toString() {
        if (this == Params.NN || this == Params.N) {
            return String.format("#0x%X", this.immediateVal);
        }
        return super.toString();
    }
}

enum Instruction {
    LD,
    WLD, // For simplifying impl 16bit LD
    LDHL,
    LDD, // same as LD A, (HL-) ... LD A, (HLD)
    LDI, // same as LD A, (HL+) ... LD A, (HLI)
    PUSH,
    POP,
    ADD,
    WADD, // 16bit ADD
    ADC,
    SUB,
    WSUB, // 16bit SUB
    SBC,
    AND,
    XOR,
    OR,
    CP,
    INC,
    WINC, // 16bit INC
    DEC,
    WDEC, // 16bit DEC
    DAA,
    CPL,
    RLCA,
    RLA,
    RRCA,
    RRA,
    RLC,
    RL,
    RRC,
    RR,
    SLA,
    SWAP,
    SRA,
    SRL,
    BIT,
    SET,
    RES,
    CCF,
    SCF,
    NOP,
    HALT,
    STOP,
    DI,
    EI,
    JP,
    JR,
    CALL,
    RET,
    RETI,
    RST,
    ILL, // Illegal
}

record InstructionInfo(int op, Instruction instruction, Params to, Params from,
                              int cycle) {
    private final static InstructionInfo[] instArr = {
            new InstructionInfo(0x00, Instruction.NOP, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x01, Instruction.WLD, Params.BC, Params.NN, 12),
            new InstructionInfo(0x02, Instruction.LD, Params.BC, Params.A, 8),
            new InstructionInfo(0x03, Instruction.WINC, Params.BC, Params.BC, 8),
            new InstructionInfo(0x04, Instruction.INC, Params.B, Params.B, 4),
            new InstructionInfo(0x05, Instruction.DEC, Params.B, Params.B, 4),
            new InstructionInfo(0x06, Instruction.LD, Params.B, Params.N, 8),
            new InstructionInfo(0x07, Instruction.RLCA, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x08, Instruction.WLD, Params.NN, Params.SP, 20),
            new InstructionInfo(0x09, Instruction.WADD, Params.HL, Params.BC, 8),
            new InstructionInfo(0x0A, Instruction.LD, Params.A, Params.BC, 8),
            new InstructionInfo(0x0B, Instruction.WDEC, Params.BC, Params.BC, 8),
            new InstructionInfo(0x0C, Instruction.INC, Params.C, Params.C, 4),
            new InstructionInfo(0x0D, Instruction.DEC, Params.C, Params.C, 4),
            new InstructionInfo(0x0E, Instruction.LD, Params.C, Params.N, 8),
            new InstructionInfo(0x0F, Instruction.RRCA, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x10, Instruction.STOP, Params.N, Params.NONE, 4),
            new InstructionInfo(0x11, Instruction.WLD, Params.DE, Params.NN, 12),
            new InstructionInfo(0x12, Instruction.LD, Params.DE, Params.A, 8),
            new InstructionInfo(0x13, Instruction.WINC, Params.DE, Params.DE, 8),
            new InstructionInfo(0x14, Instruction.INC, Params.D, Params.D, 4),
            new InstructionInfo(0x15, Instruction.DEC, Params.D, Params.D, 4),
            new InstructionInfo(0x16, Instruction.LD, Params.D, Params.N, 8),
            new InstructionInfo(0x17, Instruction.RLA, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x18, Instruction.JR, Params.PC, Params.N, 12),
            new InstructionInfo(0x19, Instruction.WADD, Params.HL, Params.DE, 8),
            new InstructionInfo(0x1A, Instruction.LD, Params.A, Params.DE, 8),
            new InstructionInfo(0x1B, Instruction.WDEC, Params.DE, Params.DE, 8),
            new InstructionInfo(0x1C, Instruction.INC, Params.E, Params.E, 4),
            new InstructionInfo(0x1D, Instruction.DEC, Params.E, Params.E, 4),
            new InstructionInfo(0x1E, Instruction.LD, Params.E, Params.N, 8),
            new InstructionInfo(0x1F, Instruction.RRA, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x20, Instruction.JR, Params.CC_NZ, Params.N, 12),
            new InstructionInfo(0x21, Instruction.WLD, Params.HL, Params.NN, 12),
            new InstructionInfo(0x22, Instruction.LDI, Params.HL, Params.A, 8),
            new InstructionInfo(0x23, Instruction.WINC, Params.HL, Params.HL, 8),
            new InstructionInfo(0x24, Instruction.INC, Params.H, Params.H, 4),
            new InstructionInfo(0x25, Instruction.DEC, Params.H, Params.H, 4),
            new InstructionInfo(0x26, Instruction.LD, Params.H, Params.N, 8),
            new InstructionInfo(0x27, Instruction.DAA, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x28, Instruction.JR, Params.CC_Z, Params.N, 8),
            new InstructionInfo(0x29, Instruction.WADD, Params.HL, Params.HL, 8),
            new InstructionInfo(0x2A, Instruction.LDI, Params.A, Params.HL, 8),
            new InstructionInfo(0x2B, Instruction.WDEC, Params.HL, Params.HL, 8),
            new InstructionInfo(0x2C, Instruction.INC, Params.L, Params.L, 4),
            new InstructionInfo(0x2D, Instruction.DEC, Params.L, Params.L, 4),
            new InstructionInfo(0x2E, Instruction.LD, Params.L, Params.N, 8),
            new InstructionInfo(0x2F, Instruction.CPL, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x30, Instruction.JR, Params.CC_NC, Params.N, 8),
            new InstructionInfo(0x31, Instruction.WLD, Params.SP, Params.NN, 12),
            new InstructionInfo(0x32, Instruction.LDD, Params.HL, Params.A, 8),
            new InstructionInfo(0x33, Instruction.WINC, Params.SP, Params.SP, 8),
            new InstructionInfo(0x34, Instruction.INC, Params.HL, Params.HL, 12),
            new InstructionInfo(0x35, Instruction.DEC, Params.HL, Params.HL, 12),
            new InstructionInfo(0x36, Instruction.LD, Params.HL, Params.N, 12),
            new InstructionInfo(0x37, Instruction.SCF, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x38, Instruction.JR, Params.CC_C, Params.N, 8),
            new InstructionInfo(0x39, Instruction.WADD, Params.HL, Params.SP, 8),
            new InstructionInfo(0x3A, Instruction.LDD, Params.A, Params.HL, 8),
            new InstructionInfo(0x3B, Instruction.WDEC, Params.SP, Params.SP, 8),
            new InstructionInfo(0x3C, Instruction.INC, Params.A, Params.A, 4),
            new InstructionInfo(0x3D, Instruction.DEC, Params.A, Params.A, 4),
            new InstructionInfo(0x3E, Instruction.LD, Params.A, Params.N, 8),
            new InstructionInfo(0x3F, Instruction.CCF, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x40, Instruction.LD, Params.B, Params.B, 4),
            new InstructionInfo(0x41, Instruction.LD, Params.B, Params.C, 4),
            new InstructionInfo(0x42, Instruction.LD, Params.B, Params.D, 4),
            new InstructionInfo(0x43, Instruction.LD, Params.B, Params.E, 4),
            new InstructionInfo(0x44, Instruction.LD, Params.B, Params.H, 4),
            new InstructionInfo(0x45, Instruction.LD, Params.B, Params.L, 4),
            new InstructionInfo(0x46, Instruction.LD, Params.B, Params.HL, 8),
            new InstructionInfo(0x47, Instruction.LD, Params.B, Params.A, 4),
            new InstructionInfo(0x48, Instruction.LD, Params.C, Params.B, 4),
            new InstructionInfo(0x49, Instruction.LD, Params.C, Params.C, 4),
            new InstructionInfo(0x4A, Instruction.LD, Params.C, Params.D, 4),
            new InstructionInfo(0x4B, Instruction.LD, Params.C, Params.E, 4),
            new InstructionInfo(0x4C, Instruction.LD, Params.C, Params.H, 4),
            new InstructionInfo(0x4D, Instruction.LD, Params.C, Params.L, 4),
            new InstructionInfo(0x4E, Instruction.LD, Params.C, Params.HL, 8),
            new InstructionInfo(0x4F, Instruction.LD, Params.C, Params.A, 4),
            new InstructionInfo(0x50, Instruction.LD, Params.D, Params.B, 4),
            new InstructionInfo(0x51, Instruction.LD, Params.D, Params.C, 4),
            new InstructionInfo(0x52, Instruction.LD, Params.D, Params.D, 4),
            new InstructionInfo(0x53, Instruction.LD, Params.D, Params.E, 4),
            new InstructionInfo(0x54, Instruction.LD, Params.D, Params.H, 4),
            new InstructionInfo(0x55, Instruction.LD, Params.D, Params.L, 4),
            new InstructionInfo(0x56, Instruction.LD, Params.D, Params.HL, 8),
            new InstructionInfo(0x57, Instruction.LD, Params.D, Params.A, 4),
            new InstructionInfo(0x58, Instruction.LD, Params.E, Params.B, 4),
            new InstructionInfo(0x59, Instruction.LD, Params.E, Params.C, 4),
            new InstructionInfo(0x5A, Instruction.LD, Params.E, Params.D, 4),
            new InstructionInfo(0x5B, Instruction.LD, Params.E, Params.E, 4),
            new InstructionInfo(0x5C, Instruction.LD, Params.E, Params.H, 4),
            new InstructionInfo(0x5D, Instruction.LD, Params.E, Params.L, 4),
            new InstructionInfo(0x5E, Instruction.LD, Params.E, Params.HL, 8),
            new InstructionInfo(0x5F, Instruction.LD, Params.E, Params.A, 4),
            new InstructionInfo(0x60, Instruction.LD, Params.H, Params.B, 4),
            new InstructionInfo(0x61, Instruction.LD, Params.H, Params.C, 4),
            new InstructionInfo(0x62, Instruction.LD, Params.H, Params.D, 4),
            new InstructionInfo(0x63, Instruction.LD, Params.H, Params.E, 4),
            new InstructionInfo(0x64, Instruction.LD, Params.H, Params.H, 4),
            new InstructionInfo(0x65, Instruction.LD, Params.H, Params.L, 4),
            new InstructionInfo(0x66, Instruction.LD, Params.H, Params.HL, 8),
            new InstructionInfo(0x67, Instruction.LD, Params.H, Params.A, 4),
            new InstructionInfo(0x68, Instruction.LD, Params.L, Params.B, 4),
            new InstructionInfo(0x69, Instruction.LD, Params.L, Params.C, 4),
            new InstructionInfo(0x6A, Instruction.LD, Params.L, Params.D, 4),
            new InstructionInfo(0x6B, Instruction.LD, Params.L, Params.E, 4),
            new InstructionInfo(0x6C, Instruction.LD, Params.L, Params.H, 4),
            new InstructionInfo(0x6D, Instruction.LD, Params.L, Params.L, 4),
            new InstructionInfo(0x6E, Instruction.LD, Params.L, Params.HL, 8),
            new InstructionInfo(0x6F, Instruction.LD, Params.L, Params.A, 4),
            new InstructionInfo(0x70, Instruction.LD, Params.HL, Params.B, 8),
            new InstructionInfo(0x71, Instruction.LD, Params.HL, Params.C, 8),
            new InstructionInfo(0x72, Instruction.LD, Params.HL, Params.D, 8),
            new InstructionInfo(0x73, Instruction.LD, Params.HL, Params.E, 8),
            new InstructionInfo(0x74, Instruction.LD, Params.HL, Params.H, 8),
            new InstructionInfo(0x75, Instruction.LD, Params.HL, Params.L, 8),
            new InstructionInfo(0x76, Instruction.HALT, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0x77, Instruction.LD, Params.HL, Params.A, 8),
            new InstructionInfo(0x78, Instruction.LD, Params.A, Params.B, 4),
            new InstructionInfo(0x79, Instruction.LD, Params.A, Params.C, 4),
            new InstructionInfo(0x7A, Instruction.LD, Params.A, Params.D, 4),
            new InstructionInfo(0x7B, Instruction.LD, Params.A, Params.E, 4),
            new InstructionInfo(0x7C, Instruction.LD, Params.A, Params.H, 4),
            new InstructionInfo(0x7D, Instruction.LD, Params.A, Params.L, 4),
            new InstructionInfo(0x7E, Instruction.LD, Params.A, Params.HL, 8),
            new InstructionInfo(0x7F, Instruction.LD, Params.A, Params.A, 4),
            new InstructionInfo(0x80, Instruction.ADD, Params.A, Params.B, 4),
            new InstructionInfo(0x81, Instruction.ADD, Params.A, Params.C, 4),
            new InstructionInfo(0x82, Instruction.ADD, Params.A, Params.D, 4),
            new InstructionInfo(0x83, Instruction.ADD, Params.A, Params.E, 4),
            new InstructionInfo(0x84, Instruction.ADD, Params.A, Params.H, 4),
            new InstructionInfo(0x85, Instruction.ADD, Params.A, Params.L, 4),
            new InstructionInfo(0x86, Instruction.ADD, Params.A, Params.HL, 8),
            new InstructionInfo(0x87, Instruction.ADD, Params.A, Params.A, 4),
            new InstructionInfo(0x88, Instruction.ADC, Params.A, Params.B, 4),
            new InstructionInfo(0x89, Instruction.ADC, Params.A, Params.C, 4),
            new InstructionInfo(0x8A, Instruction.ADC, Params.A, Params.D, 4),
            new InstructionInfo(0x8B, Instruction.ADC, Params.A, Params.E, 4),
            new InstructionInfo(0x8C, Instruction.ADC, Params.A, Params.H, 4),
            new InstructionInfo(0x8D, Instruction.ADC, Params.A, Params.L, 4),
            new InstructionInfo(0x8E, Instruction.ADC, Params.A, Params.HL, 8),
            new InstructionInfo(0x8F, Instruction.ADC, Params.A, Params.A, 4),
            new InstructionInfo(0x90, Instruction.SUB, Params.A, Params.B, 4),
            new InstructionInfo(0x91, Instruction.SUB, Params.A, Params.C, 4),
            new InstructionInfo(0x92, Instruction.SUB, Params.A, Params.D, 4),
            new InstructionInfo(0x93, Instruction.SUB, Params.A, Params.E, 4),
            new InstructionInfo(0x94, Instruction.SUB, Params.A, Params.H, 4),
            new InstructionInfo(0x95, Instruction.SUB, Params.A, Params.L, 4),
            new InstructionInfo(0x96, Instruction.SUB, Params.A, Params.HL, 8),
            new InstructionInfo(0x97, Instruction.SUB, Params.A, Params.A, 4),
            new InstructionInfo(0x98, Instruction.SBC, Params.A, Params.B, 4),
            new InstructionInfo(0x99, Instruction.SBC, Params.A, Params.C, 4),
            new InstructionInfo(0x9A, Instruction.SBC, Params.A, Params.D, 4),
            new InstructionInfo(0x9B, Instruction.SBC, Params.A, Params.E, 4),
            new InstructionInfo(0x9C, Instruction.SBC, Params.A, Params.H, 4),
            new InstructionInfo(0x9D, Instruction.SBC, Params.A, Params.L, 4),
            new InstructionInfo(0x9E, Instruction.SBC, Params.A, Params.HL, 8),
            new InstructionInfo(0x9F, Instruction.SBC, Params.A, Params.A, 4),
            new InstructionInfo(0xA0, Instruction.AND, Params.A, Params.B, 4),
            new InstructionInfo(0xA1, Instruction.AND, Params.A, Params.C, 4),
            new InstructionInfo(0xA2, Instruction.AND, Params.A, Params.D, 4),
            new InstructionInfo(0xA3, Instruction.AND, Params.A, Params.E, 4),
            new InstructionInfo(0xA4, Instruction.AND, Params.A, Params.H, 4),
            new InstructionInfo(0xA5, Instruction.AND, Params.A, Params.L, 4),
            new InstructionInfo(0xA6, Instruction.AND, Params.A, Params.HL, 8),
            new InstructionInfo(0xA7, Instruction.AND, Params.A, Params.A, 4),
            new InstructionInfo(0xA8, Instruction.XOR, Params.A, Params.B, 4),
            new InstructionInfo(0xA9, Instruction.XOR, Params.A, Params.C, 4),
            new InstructionInfo(0xAA, Instruction.XOR, Params.A, Params.D, 4),
            new InstructionInfo(0xAB, Instruction.XOR, Params.A, Params.E, 4),
            new InstructionInfo(0xAC, Instruction.XOR, Params.A, Params.H, 4),
            new InstructionInfo(0xAD, Instruction.XOR, Params.A, Params.L, 4),
            new InstructionInfo(0xAE, Instruction.XOR, Params.A, Params.HL, 8),
            new InstructionInfo(0xAF, Instruction.XOR, Params.A, Params.A, 4),
            new InstructionInfo(0xB0, Instruction.OR, Params.A, Params.B, 4),
            new InstructionInfo(0xB1, Instruction.OR, Params.A, Params.C, 4),
            new InstructionInfo(0xB2, Instruction.OR, Params.A, Params.D, 4),
            new InstructionInfo(0xB3, Instruction.OR, Params.A, Params.E, 4),
            new InstructionInfo(0xB4, Instruction.OR, Params.A, Params.H, 4),
            new InstructionInfo(0xB5, Instruction.OR, Params.A, Params.L, 4),
            new InstructionInfo(0xB6, Instruction.OR, Params.A, Params.HL, 8),
            new InstructionInfo(0xB7, Instruction.OR, Params.A, Params.A, 4),
            new InstructionInfo(0xB8, Instruction.CP, Params.A, Params.B, 4),
            new InstructionInfo(0xB9, Instruction.CP, Params.A, Params.C, 4),
            new InstructionInfo(0xBA, Instruction.CP, Params.A, Params.D, 4),
            new InstructionInfo(0xBB, Instruction.CP, Params.A, Params.E, 4),
            new InstructionInfo(0xBC, Instruction.CP, Params.A, Params.H, 4),
            new InstructionInfo(0xBD, Instruction.CP, Params.A, Params.L, 4),
            new InstructionInfo(0xBE, Instruction.CP, Params.A, Params.HL, 8),
            new InstructionInfo(0xBF, Instruction.CP, Params.A, Params.A, 4),
            new InstructionInfo(0xC0, Instruction.RET, Params.CC_NZ, Params.NONE, 8),
            new InstructionInfo(0xC1, Instruction.POP, Params.BC, Params.SP, 12),
            new InstructionInfo(0xC2, Instruction.JP, Params.CC_NZ, Params.NN, 12),
            new InstructionInfo(0xC3, Instruction.JP, Params.PC, Params.NN, 12),
            new InstructionInfo(0xC4, Instruction.CALL, Params.CC_NZ, Params.NN, 12),
            new InstructionInfo(0xC5, Instruction.PUSH, Params.SP, Params.BC, 16),
            new InstructionInfo(0xC6, Instruction.ADD, Params.A, Params.N, 8),
            new InstructionInfo(0xC7, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xC8, Instruction.RET, Params.CC_Z, Params.NONE, 8),
            new InstructionInfo(0xC9, Instruction.RET, Params.NONE, Params.NONE, 8),
            new InstructionInfo(0xCA, Instruction.JP, Params.CC_Z, Params.NN, 12),
            new InstructionInfo(0xCB, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xCC, Instruction.CALL, Params.CC_Z, Params.NN, 12),
            new InstructionInfo(0xCD, Instruction.CALL, Params.NONE, Params.NN, 12),
            new InstructionInfo(0xCE, Instruction.ADC, Params.A, Params.N, 8),
            new InstructionInfo(0xCF, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xD0, Instruction.RET, Params.CC_NC, Params.NONE, 8),
            new InstructionInfo(0xD1, Instruction.POP, Params.DE, Params.SP, 12),
            new InstructionInfo(0xD2, Instruction.JP, Params.CC_NC, Params.NN, 12),
            new InstructionInfo(0xD3, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xD4, Instruction.CALL, Params.CC_NC, Params.NN, 12),
            new InstructionInfo(0xD5, Instruction.PUSH, Params.SP, Params.DE, 16),
            new InstructionInfo(0xD6, Instruction.SUB, Params.A, Params.N, 8),
            new InstructionInfo(0xD7, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xD8, Instruction.RET, Params.CC_C, Params.NONE, 8),
            new InstructionInfo(0xD9, Instruction.RETI, Params.NONE, Params.NONE, 8),
            new InstructionInfo(0xDA, Instruction.JP, Params.CC_C, Params.NN, 12),
            new InstructionInfo(0xDB, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xDC, Instruction.CALL, Params.CC_C, Params.NN, 12),
            new InstructionInfo(0xDD, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xDE, Instruction.SBC, Params.A, Params.N, 8),
            new InstructionInfo(0xDF, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xE0, Instruction.LD, Params.INDEXED_N, Params.A, 12),
            new InstructionInfo(0xE1, Instruction.POP, Params.HL, Params.SP, 12),
            new InstructionInfo(0xE2, Instruction.LD, Params.INDEXED_C, Params.A, 8),
            new InstructionInfo(0xE3, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xE4, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xE5, Instruction.PUSH, Params.SP, Params.HL, 16),
            new InstructionInfo(0xE6, Instruction.AND, Params.A, Params.N, 8),
            new InstructionInfo(0xE7, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xE8, Instruction.WADD, Params.SP, Params.N, 16),
            new InstructionInfo(0xE9, Instruction.JP, Params.PC, Params.HL, 4),
            new InstructionInfo(0xEA, Instruction.LD, Params.NN, Params.A, 16),
            new InstructionInfo(0xEB, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xEC, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xED, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xEE, Instruction.XOR, Params.A, Params.N, 8),
            new InstructionInfo(0xEF, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xF0, Instruction.LD, Params.A, Params.INDEXED_N, 12),
            new InstructionInfo(0xF1, Instruction.POP, Params.AF, Params.SP, 12),
            new InstructionInfo(0xF2, Instruction.LD, Params.A, Params.INDEXED_C, 8),
            new InstructionInfo(0xF3, Instruction.DI, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0xF4, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xF5, Instruction.PUSH, Params.SP, Params.AF, 16),
            new InstructionInfo(0xF6, Instruction.OR, Params.A, Params.N, 8),
            new InstructionInfo(0xF7, Instruction.RST, Params.PC, Params.NONE, 32),
            new InstructionInfo(0xF8, Instruction.LDHL, Params.SP, Params.N, 12),
            new InstructionInfo(0xF9, Instruction.WLD, Params.SP, Params.HL, 8),
            new InstructionInfo(0xFA, Instruction.LD, Params.A, Params.NN, 16),
            new InstructionInfo(0xFB, Instruction.EI, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0xFC, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xFD, Instruction.ILL, Params.NONE, Params.NONE, 0),
            new InstructionInfo(0xFE, Instruction.CP, Params.A, Params.N, 8),
            new InstructionInfo(0xFF, Instruction.RST, Params.PC, Params.NONE, 32),
    };

    private final static InstructionInfo[] prefixedInstArr = {
            new InstructionInfo(0x00, Instruction.RLC, Params.B, Params.B, 8),
            new InstructionInfo(0x01, Instruction.RLC, Params.C, Params.C, 8),
            new InstructionInfo(0x02, Instruction.RLC, Params.D, Params.D, 8),
            new InstructionInfo(0x03, Instruction.RLC, Params.E, Params.E, 8),
            new InstructionInfo(0x04, Instruction.RLC, Params.H, Params.H, 8),
            new InstructionInfo(0x05, Instruction.RLC, Params.L, Params.L, 8),
            new InstructionInfo(0x06, Instruction.RLC, Params.HL, Params.HL, 16),
            new InstructionInfo(0x07, Instruction.RLC, Params.A, Params.A, 8),
            new InstructionInfo(0x08, Instruction.RRC, Params.B, Params.B, 8),
            new InstructionInfo(0x09, Instruction.RRC, Params.C, Params.C, 8),
            new InstructionInfo(0x0A, Instruction.RRC, Params.D, Params.D, 8),
            new InstructionInfo(0x0B, Instruction.RRC, Params.E, Params.E, 8),
            new InstructionInfo(0x0C, Instruction.RRC, Params.H, Params.H, 8),
            new InstructionInfo(0x0D, Instruction.RRC, Params.L, Params.L, 8),
            new InstructionInfo(0x0E, Instruction.RRC, Params.HL, Params.HL, 16),
            new InstructionInfo(0x0F, Instruction.RRC, Params.A, Params.A, 8),
            new InstructionInfo(0x10, Instruction.RL, Params.B, Params.B, 8),
            new InstructionInfo(0x11, Instruction.RL, Params.C, Params.C, 8),
            new InstructionInfo(0x12, Instruction.RL, Params.D, Params.D, 8),
            new InstructionInfo(0x13, Instruction.RL, Params.E, Params.E, 8),
            new InstructionInfo(0x14, Instruction.RL, Params.H, Params.H, 8),
            new InstructionInfo(0x15, Instruction.RL, Params.L, Params.L, 8),
            new InstructionInfo(0x16, Instruction.RL, Params.HL, Params.HL, 16),
            new InstructionInfo(0x17, Instruction.RL, Params.A, Params.A, 8),
            new InstructionInfo(0x18, Instruction.RR, Params.B, Params.B, 8),
            new InstructionInfo(0x19, Instruction.RR, Params.C, Params.C, 8),
            new InstructionInfo(0x1A, Instruction.RR, Params.D, Params.D, 8),
            new InstructionInfo(0x1B, Instruction.RR, Params.E, Params.E, 8),
            new InstructionInfo(0x1C, Instruction.RR, Params.H, Params.H, 8),
            new InstructionInfo(0x1D, Instruction.RR, Params.L, Params.L, 8),
            new InstructionInfo(0x1E, Instruction.RR, Params.HL, Params.HL, 16),
            new InstructionInfo(0x1F, Instruction.RR, Params.A, Params.A, 8),
            new InstructionInfo(0x20, Instruction.SLA, Params.B, Params.B, 8),
            new InstructionInfo(0x21, Instruction.SLA, Params.C, Params.C, 8),
            new InstructionInfo(0x22, Instruction.SLA, Params.D, Params.D, 8),
            new InstructionInfo(0x23, Instruction.SLA, Params.E, Params.E, 8),
            new InstructionInfo(0x24, Instruction.SLA, Params.H, Params.H, 8),
            new InstructionInfo(0x25, Instruction.SLA, Params.L, Params.L, 8),
            new InstructionInfo(0x26, Instruction.SLA, Params.HL, Params.HL, 16),
            new InstructionInfo(0x27, Instruction.SLA, Params.A, Params.A, 8),
            new InstructionInfo(0x28, Instruction.SRA, Params.B, Params.B, 8),
            new InstructionInfo(0x29, Instruction.SRA, Params.C, Params.C, 8),
            new InstructionInfo(0x2A, Instruction.SRA, Params.D, Params.D, 8),
            new InstructionInfo(0x2B, Instruction.SRA, Params.E, Params.E, 8),
            new InstructionInfo(0x2C, Instruction.SRA, Params.H, Params.H, 8),
            new InstructionInfo(0x2D, Instruction.SRA, Params.L, Params.L, 8),
            new InstructionInfo(0x2E, Instruction.SRA, Params.HL, Params.HL, 16),
            new InstructionInfo(0x2F, Instruction.SRA, Params.A, Params.A, 8),
            new InstructionInfo(0x30, Instruction.SWAP, Params.B, Params.B, 8),
            new InstructionInfo(0x31, Instruction.SWAP, Params.C, Params.C, 8),
            new InstructionInfo(0x32, Instruction.SWAP, Params.D, Params.D, 8),
            new InstructionInfo(0x33, Instruction.SWAP, Params.E, Params.E, 8),
            new InstructionInfo(0x34, Instruction.SWAP, Params.H, Params.H, 8),
            new InstructionInfo(0x35, Instruction.SWAP, Params.L, Params.L, 8),
            new InstructionInfo(0x36, Instruction.SWAP, Params.HL, Params.HL, 16),
            new InstructionInfo(0x37, Instruction.SWAP, Params.A, Params.A, 8),
            new InstructionInfo(0x38, Instruction.SRL, Params.B, Params.B, 8),
            new InstructionInfo(0x39, Instruction.SRL, Params.C, Params.C, 8),
            new InstructionInfo(0x3A, Instruction.SRL, Params.D, Params.D, 8),
            new InstructionInfo(0x3B, Instruction.SRL, Params.E, Params.E, 8),
            new InstructionInfo(0x3C, Instruction.SRL, Params.H, Params.H, 8),
            new InstructionInfo(0x3D, Instruction.SRL, Params.L, Params.L, 8),
            new InstructionInfo(0x3E, Instruction.SRL, Params.HL, Params.HL, 16),
            new InstructionInfo(0x3F, Instruction.SRL, Params.A, Params.A, 8),
            new InstructionInfo(0x40, Instruction.BIT, Params.BIT0, Params.B, 8),
            new InstructionInfo(0x41, Instruction.BIT, Params.BIT0, Params.C, 8),
            new InstructionInfo(0x42, Instruction.BIT, Params.BIT0, Params.D, 8),
            new InstructionInfo(0x43, Instruction.BIT, Params.BIT0, Params.E, 8),
            new InstructionInfo(0x44, Instruction.BIT, Params.BIT0, Params.H, 8),
            new InstructionInfo(0x45, Instruction.BIT, Params.BIT0, Params.L, 8),
            new InstructionInfo(0x46, Instruction.BIT, Params.BIT0, Params.HL, 12),
            new InstructionInfo(0x47, Instruction.BIT, Params.BIT0, Params.A, 8),
            new InstructionInfo(0x48, Instruction.BIT, Params.BIT1, Params.B, 8),
            new InstructionInfo(0x49, Instruction.BIT, Params.BIT1, Params.C, 8),
            new InstructionInfo(0x4A, Instruction.BIT, Params.BIT1, Params.D, 8),
            new InstructionInfo(0x4B, Instruction.BIT, Params.BIT1, Params.E, 8),
            new InstructionInfo(0x4C, Instruction.BIT, Params.BIT1, Params.H, 8),
            new InstructionInfo(0x4D, Instruction.BIT, Params.BIT1, Params.L, 8),
            new InstructionInfo(0x4E, Instruction.BIT, Params.BIT1, Params.HL, 12),
            new InstructionInfo(0x4F, Instruction.BIT, Params.BIT1, Params.A, 8),
            new InstructionInfo(0x50, Instruction.BIT, Params.BIT2, Params.B, 8),
            new InstructionInfo(0x51, Instruction.BIT, Params.BIT2, Params.C, 8),
            new InstructionInfo(0x52, Instruction.BIT, Params.BIT2, Params.D, 8),
            new InstructionInfo(0x53, Instruction.BIT, Params.BIT2, Params.E, 8),
            new InstructionInfo(0x54, Instruction.BIT, Params.BIT2, Params.H, 8),
            new InstructionInfo(0x55, Instruction.BIT, Params.BIT2, Params.L, 8),
            new InstructionInfo(0x56, Instruction.BIT, Params.BIT2, Params.HL, 12),
            new InstructionInfo(0x57, Instruction.BIT, Params.BIT2, Params.A, 8),
            new InstructionInfo(0x58, Instruction.BIT, Params.BIT3, Params.B, 8),
            new InstructionInfo(0x59, Instruction.BIT, Params.BIT3, Params.C, 8),
            new InstructionInfo(0x5A, Instruction.BIT, Params.BIT3, Params.D, 8),
            new InstructionInfo(0x5B, Instruction.BIT, Params.BIT3, Params.E, 8),
            new InstructionInfo(0x5C, Instruction.BIT, Params.BIT3, Params.H, 8),
            new InstructionInfo(0x5D, Instruction.BIT, Params.BIT3, Params.L, 8),
            new InstructionInfo(0x5E, Instruction.BIT, Params.BIT3, Params.HL, 12),
            new InstructionInfo(0x5F, Instruction.BIT, Params.BIT3, Params.A, 8),
            new InstructionInfo(0x60, Instruction.BIT, Params.BIT4, Params.B, 8),
            new InstructionInfo(0x61, Instruction.BIT, Params.BIT4, Params.C, 8),
            new InstructionInfo(0x62, Instruction.BIT, Params.BIT4, Params.D, 8),
            new InstructionInfo(0x63, Instruction.BIT, Params.BIT4, Params.E, 8),
            new InstructionInfo(0x64, Instruction.BIT, Params.BIT4, Params.H, 8),
            new InstructionInfo(0x65, Instruction.BIT, Params.BIT4, Params.L, 8),
            new InstructionInfo(0x66, Instruction.BIT, Params.BIT4, Params.HL, 12),
            new InstructionInfo(0x67, Instruction.BIT, Params.BIT4, Params.A, 8),
            new InstructionInfo(0x68, Instruction.BIT, Params.BIT5, Params.B, 8),
            new InstructionInfo(0x69, Instruction.BIT, Params.BIT5, Params.C, 8),
            new InstructionInfo(0x6A, Instruction.BIT, Params.BIT5, Params.D, 8),
            new InstructionInfo(0x6B, Instruction.BIT, Params.BIT5, Params.E, 8),
            new InstructionInfo(0x6C, Instruction.BIT, Params.BIT5, Params.H, 8),
            new InstructionInfo(0x6D, Instruction.BIT, Params.BIT5, Params.L, 8),
            new InstructionInfo(0x6E, Instruction.BIT, Params.BIT5, Params.HL, 12),
            new InstructionInfo(0x6F, Instruction.BIT, Params.BIT5, Params.A, 8),
            new InstructionInfo(0x70, Instruction.BIT, Params.BIT6, Params.B, 8),
            new InstructionInfo(0x71, Instruction.BIT, Params.BIT6, Params.C, 8),
            new InstructionInfo(0x72, Instruction.BIT, Params.BIT6, Params.D, 8),
            new InstructionInfo(0x73, Instruction.BIT, Params.BIT6, Params.E, 8),
            new InstructionInfo(0x74, Instruction.BIT, Params.BIT6, Params.H, 8),
            new InstructionInfo(0x75, Instruction.BIT, Params.BIT6, Params.L, 8),
            new InstructionInfo(0x76, Instruction.BIT, Params.BIT6, Params.HL, 12),
            new InstructionInfo(0x77, Instruction.BIT, Params.BIT6, Params.A, 8),
            new InstructionInfo(0x78, Instruction.BIT, Params.BIT7, Params.B, 8),
            new InstructionInfo(0x79, Instruction.BIT, Params.BIT7, Params.C, 8),
            new InstructionInfo(0x7A, Instruction.BIT, Params.BIT7, Params.D, 8),
            new InstructionInfo(0x7B, Instruction.BIT, Params.BIT7, Params.E, 8),
            new InstructionInfo(0x7C, Instruction.BIT, Params.BIT7, Params.H, 8),
            new InstructionInfo(0x7D, Instruction.BIT, Params.BIT7, Params.L, 8),
            new InstructionInfo(0x7E, Instruction.BIT, Params.BIT7, Params.HL, 12),
            new InstructionInfo(0x7F, Instruction.BIT, Params.BIT7, Params.A, 8),
            new InstructionInfo(0x80, Instruction.RES, Params.BIT0, Params.B, 8),
            new InstructionInfo(0x81, Instruction.RES, Params.BIT0, Params.C, 8),
            new InstructionInfo(0x82, Instruction.RES, Params.BIT0, Params.D, 8),
            new InstructionInfo(0x83, Instruction.RES, Params.BIT0, Params.E, 8),
            new InstructionInfo(0x84, Instruction.RES, Params.BIT0, Params.H, 8),
            new InstructionInfo(0x85, Instruction.RES, Params.BIT0, Params.L, 8),
            new InstructionInfo(0x86, Instruction.RES, Params.BIT0, Params.HL, 16),
            new InstructionInfo(0x87, Instruction.RES, Params.BIT0, Params.A, 8),
            new InstructionInfo(0x88, Instruction.RES, Params.BIT1, Params.B, 8),
            new InstructionInfo(0x89, Instruction.RES, Params.BIT1, Params.C, 8),
            new InstructionInfo(0x8A, Instruction.RES, Params.BIT1, Params.D, 8),
            new InstructionInfo(0x8B, Instruction.RES, Params.BIT1, Params.E, 8),
            new InstructionInfo(0x8C, Instruction.RES, Params.BIT1, Params.H, 8),
            new InstructionInfo(0x8D, Instruction.RES, Params.BIT1, Params.L, 8),
            new InstructionInfo(0x8E, Instruction.RES, Params.BIT1, Params.HL, 16),
            new InstructionInfo(0x8F, Instruction.RES, Params.BIT1, Params.A, 8),
            new InstructionInfo(0x90, Instruction.RES, Params.BIT2, Params.B, 8),
            new InstructionInfo(0x91, Instruction.RES, Params.BIT2, Params.C, 8),
            new InstructionInfo(0x92, Instruction.RES, Params.BIT2, Params.D, 8),
            new InstructionInfo(0x93, Instruction.RES, Params.BIT2, Params.E, 8),
            new InstructionInfo(0x94, Instruction.RES, Params.BIT2, Params.H, 8),
            new InstructionInfo(0x95, Instruction.RES, Params.BIT2, Params.L, 8),
            new InstructionInfo(0x96, Instruction.RES, Params.BIT2, Params.HL, 16),
            new InstructionInfo(0x97, Instruction.RES, Params.BIT2, Params.A, 8),
            new InstructionInfo(0x98, Instruction.RES, Params.BIT3, Params.B, 8),
            new InstructionInfo(0x99, Instruction.RES, Params.BIT3, Params.C, 8),
            new InstructionInfo(0x9A, Instruction.RES, Params.BIT3, Params.D, 8),
            new InstructionInfo(0x9B, Instruction.RES, Params.BIT3, Params.E, 8),
            new InstructionInfo(0x9C, Instruction.RES, Params.BIT3, Params.H, 8),
            new InstructionInfo(0x9D, Instruction.RES, Params.BIT3, Params.L, 8),
            new InstructionInfo(0x9E, Instruction.RES, Params.BIT3, Params.HL, 16),
            new InstructionInfo(0x9F, Instruction.RES, Params.BIT3, Params.A, 8),
            new InstructionInfo(0xA0, Instruction.RES, Params.BIT4, Params.B, 8),
            new InstructionInfo(0xA1, Instruction.RES, Params.BIT4, Params.C, 8),
            new InstructionInfo(0xA2, Instruction.RES, Params.BIT4, Params.D, 8),
            new InstructionInfo(0xA3, Instruction.RES, Params.BIT4, Params.E, 8),
            new InstructionInfo(0xA4, Instruction.RES, Params.BIT4, Params.H, 8),
            new InstructionInfo(0xA5, Instruction.RES, Params.BIT4, Params.L, 8),
            new InstructionInfo(0xA6, Instruction.RES, Params.BIT4, Params.HL, 16),
            new InstructionInfo(0xA7, Instruction.RES, Params.BIT4, Params.A, 8),
            new InstructionInfo(0xA8, Instruction.RES, Params.BIT5, Params.B, 8),
            new InstructionInfo(0xA9, Instruction.RES, Params.BIT5, Params.C, 8),
            new InstructionInfo(0xAA, Instruction.RES, Params.BIT5, Params.D, 8),
            new InstructionInfo(0xAB, Instruction.RES, Params.BIT5, Params.E, 8),
            new InstructionInfo(0xAC, Instruction.RES, Params.BIT5, Params.H, 8),
            new InstructionInfo(0xAD, Instruction.RES, Params.BIT5, Params.L, 8),
            new InstructionInfo(0xAE, Instruction.RES, Params.BIT5, Params.HL, 16),
            new InstructionInfo(0xAF, Instruction.RES, Params.BIT5, Params.A, 8),
            new InstructionInfo(0xB0, Instruction.RES, Params.BIT6, Params.B, 8),
            new InstructionInfo(0xB1, Instruction.RES, Params.BIT6, Params.C, 8),
            new InstructionInfo(0xB2, Instruction.RES, Params.BIT6, Params.D, 8),
            new InstructionInfo(0xB3, Instruction.RES, Params.BIT6, Params.E, 8),
            new InstructionInfo(0xB4, Instruction.RES, Params.BIT6, Params.H, 8),
            new InstructionInfo(0xB5, Instruction.RES, Params.BIT6, Params.L, 8),
            new InstructionInfo(0xB6, Instruction.RES, Params.BIT6, Params.HL, 16),
            new InstructionInfo(0xB7, Instruction.RES, Params.BIT6, Params.A, 8),
            new InstructionInfo(0xB8, Instruction.RES, Params.BIT7, Params.B, 8),
            new InstructionInfo(0xB9, Instruction.RES, Params.BIT7, Params.C, 8),
            new InstructionInfo(0xBA, Instruction.RES, Params.BIT7, Params.D, 8),
            new InstructionInfo(0xBB, Instruction.RES, Params.BIT7, Params.E, 8),
            new InstructionInfo(0xBC, Instruction.RES, Params.BIT7, Params.H, 8),
            new InstructionInfo(0xBD, Instruction.RES, Params.BIT7, Params.L, 8),
            new InstructionInfo(0xBE, Instruction.RES, Params.BIT7, Params.HL, 16),
            new InstructionInfo(0xBF, Instruction.RES, Params.BIT7, Params.A, 8),
            new InstructionInfo(0xC0, Instruction.SET, Params.BIT0, Params.B, 8),
            new InstructionInfo(0xC1, Instruction.SET, Params.BIT0, Params.C, 8),
            new InstructionInfo(0xC2, Instruction.SET, Params.BIT0, Params.D, 8),
            new InstructionInfo(0xC3, Instruction.SET, Params.BIT0, Params.E, 8),
            new InstructionInfo(0xC4, Instruction.SET, Params.BIT0, Params.H, 8),
            new InstructionInfo(0xC5, Instruction.SET, Params.BIT0, Params.L, 8),
            new InstructionInfo(0xC6, Instruction.SET, Params.BIT0, Params.HL, 16),
            new InstructionInfo(0xC7, Instruction.SET, Params.BIT0, Params.A, 8),
            new InstructionInfo(0xC8, Instruction.SET, Params.BIT1, Params.B, 8),
            new InstructionInfo(0xC9, Instruction.SET, Params.BIT1, Params.C, 8),
            new InstructionInfo(0xCA, Instruction.SET, Params.BIT1, Params.D, 8),
            new InstructionInfo(0xCC, Instruction.SET, Params.BIT1, Params.E, 8),
            new InstructionInfo(0xCC, Instruction.SET, Params.BIT1, Params.H, 8),
            new InstructionInfo(0xCD, Instruction.SET, Params.BIT1, Params.L, 8),
            new InstructionInfo(0xCE, Instruction.SET, Params.BIT1, Params.HL, 16),
            new InstructionInfo(0xCF, Instruction.SET, Params.BIT1, Params.A, 8),
            new InstructionInfo(0xD0, Instruction.SET, Params.BIT2, Params.B, 8),
            new InstructionInfo(0xD1, Instruction.SET, Params.BIT2, Params.C, 8),
            new InstructionInfo(0xD2, Instruction.SET, Params.BIT2, Params.D, 8),
            new InstructionInfo(0xD3, Instruction.SET, Params.BIT2, Params.E, 8),
            new InstructionInfo(0xD4, Instruction.SET, Params.BIT2, Params.H, 8),
            new InstructionInfo(0xD5, Instruction.SET, Params.BIT2, Params.L, 8),
            new InstructionInfo(0xD6, Instruction.SET, Params.BIT2, Params.HL, 16),
            new InstructionInfo(0xD7, Instruction.SET, Params.BIT2, Params.A, 8),
            new InstructionInfo(0xD8, Instruction.SET, Params.BIT3, Params.B, 8),
            new InstructionInfo(0xD9, Instruction.SET, Params.BIT3, Params.C, 8),
            new InstructionInfo(0xDA, Instruction.SET, Params.BIT3, Params.D, 8),
            new InstructionInfo(0xDB, Instruction.SET, Params.BIT3, Params.E, 8),
            new InstructionInfo(0xDC, Instruction.SET, Params.BIT3, Params.H, 8),
            new InstructionInfo(0xDD, Instruction.SET, Params.BIT3, Params.L, 8),
            new InstructionInfo(0xDE, Instruction.SET, Params.BIT3, Params.HL, 16),
            new InstructionInfo(0xDF, Instruction.SET, Params.BIT3, Params.A, 8),
            new InstructionInfo(0xE0, Instruction.SET, Params.BIT4, Params.B, 8),
            new InstructionInfo(0xE1, Instruction.SET, Params.BIT4, Params.C, 8),
            new InstructionInfo(0xE2, Instruction.SET, Params.BIT4, Params.D, 8),
            new InstructionInfo(0xE3, Instruction.SET, Params.BIT4, Params.E, 8),
            new InstructionInfo(0xE4, Instruction.SET, Params.BIT4, Params.H, 8),
            new InstructionInfo(0xE5, Instruction.SET, Params.BIT4, Params.L, 8),
            new InstructionInfo(0xE6, Instruction.SET, Params.BIT4, Params.HL, 16),
            new InstructionInfo(0xE7, Instruction.SET, Params.BIT4, Params.A, 8),
            new InstructionInfo(0xE8, Instruction.SET, Params.BIT5, Params.B, 8),
            new InstructionInfo(0xE9, Instruction.SET, Params.BIT5, Params.C, 8),
            new InstructionInfo(0xEA, Instruction.SET, Params.BIT5, Params.D, 8),
            new InstructionInfo(0xEB, Instruction.SET, Params.BIT5, Params.E, 8),
            new InstructionInfo(0xEC, Instruction.SET, Params.BIT5, Params.H, 8),
            new InstructionInfo(0xED, Instruction.SET, Params.BIT5, Params.L, 8),
            new InstructionInfo(0xEE, Instruction.SET, Params.BIT5, Params.HL, 16),
            new InstructionInfo(0xEF, Instruction.SET, Params.BIT5, Params.A, 8),
            new InstructionInfo(0xF0, Instruction.SET, Params.BIT6, Params.B, 8),
            new InstructionInfo(0xF1, Instruction.SET, Params.BIT6, Params.C, 8),
            new InstructionInfo(0xF2, Instruction.SET, Params.BIT6, Params.D, 8),
            new InstructionInfo(0xF3, Instruction.SET, Params.BIT6, Params.E, 8),
            new InstructionInfo(0xF4, Instruction.SET, Params.BIT6, Params.H, 8),
            new InstructionInfo(0xF5, Instruction.SET, Params.BIT6, Params.L, 8),
            new InstructionInfo(0xF6, Instruction.SET, Params.BIT6, Params.HL, 16),
            new InstructionInfo(0xF7, Instruction.SET, Params.BIT6, Params.A, 8),
            new InstructionInfo(0xF8, Instruction.SET, Params.BIT7, Params.B, 8),
            new InstructionInfo(0xF9, Instruction.SET, Params.BIT7, Params.C, 8),
            new InstructionInfo(0xFA, Instruction.SET, Params.BIT7, Params.D, 8),
            new InstructionInfo(0xFB, Instruction.SET, Params.BIT7, Params.E, 8),
            new InstructionInfo(0xFC, Instruction.SET, Params.BIT7, Params.H, 8),
            new InstructionInfo(0xFD, Instruction.SET, Params.BIT7, Params.L, 8),
            new InstructionInfo(0xFE, Instruction.SET, Params.BIT7, Params.HL, 16),
            new InstructionInfo(0xFF, Instruction.SET, Params.BIT7, Params.A, 8),
    };

    @Override
    public String toString() {
        final var inst = this.instruction.toString();
        final var to = switch (this.to) {
            case AF, BC, DE, HL, NN, SP -> "(" + this.to + ")";
            case INDEXED_C -> "($0xFF00 + C)";
            case INDEXED_N -> String.format("0x%04X", this.to.getImmediateVal());
            case BIT0 -> 0;
            case BIT1 -> 1;
            case BIT2 -> 2;
            case BIT3 -> 3;
            case BIT4 -> 4;
            case BIT5 -> 5;
            case BIT6 -> 6;
            case BIT7 -> 7;
            case NONE ->  "";
            default -> this.to;
        };
        final var from = switch (this.from) {
            case BC, DE, HL, NN -> ", (" + this.from + ")";
            case INDEXED_C -> ", ($0xFF00 + C)";
            case INDEXED_N -> String.format(", 0x%04X", this.from.getImmediateVal());
            case NONE ->  "";
            default -> ", " + this.from;
        };
        return String.format("(0x%02X) %s %s %s", op, inst, to, from);
    }

    static InstructionInfo getInstruction(int op) {
        return InstructionInfo.instArr[op];
    }

    static InstructionInfo getCBPrefixedInstruction(int op) {
        return InstructionInfo.prefixedInstArr[op];
    }
}