package devices;

enum Params {
    A,
    IN_A, // (A) register-indirect addressing
    B,
    IN_B, // (B)
    C,
    IN_C, // (C)
    INDEXED_C, // ($0xFFF0 + C)
    BC,
    D,
    IN_D, // (D)
    E,
    IN_E, // (E)
    DE,
    H,
    IN_H, // (H)
    L,
    HL,
    IN_L, // (L)
    NN(0),   //  immediate absolute address 2byte
    N(0),    //  immediate value 1byte
    INDEXED_N(0), // N(1 byte) + 0xFF00
    SP,   //  stack pointer
    NONE;

    private int immediateVal;
    Params(int immediateVal) {
        this.immediateVal = immediateVal;
    }

    Params() { }

    public void setImmediateVal(int immediateVal) {
        this.immediateVal = (this == Params.INDEXED_N) ? 0xFF00 + immediateVal : immediateVal;
    }

    public int getImmediateVal() { return this.immediateVal; }

    @Override
    public String toString() {
        if (this == Params.NN || this == Params.N) {
            return String.format("#0x%X", this.immediateVal);
        }
        return super.toString();
    }
}

enum Instruction {
    LD,
    LDD, // same as LD A, (HL-) ... LD A, (HLD)
    LDI, // same as LD A, (HL+) ... LD A, (HLI)
    PUSH,
    POP,
    ADD,
    ADC,
    SUB,
    SBC,
    AND,
    XOR,
    OR,
    CP,
    INC,
    DEC,
    DAA,
    CPL,
    RLCA,
    RLA,
    RRCA,
    RRA,
    RLC,
    RL,
    RRC,
    RR,
    SLA,
    SWAP,
    SRA,
    SRL,
    BIT,
    SET,
    RES,
    CCF,
    SCF,
    NOP,
    HALT,
    STOP,
    DI,
    EI,
    JP,
    JR,
    CALL,
    RET,
    RETI,
    RST,
    ILL, // Illegal
}

public record InstructionInfo(int op, Instruction instruction, Params to, Params from,
                              int cycle) {
    private final static InstructionInfo[] instArr = {
            new InstructionInfo(0x00, Instruction.NOP, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x01, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x02, Instruction.LD, Params.BC, Params.A, 8),
            new InstructionInfo(0x03, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x04, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x05, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x06, Instruction.LD, Params.B, Params.N, 8),
            new InstructionInfo(0x07, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x08, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x09, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0A, Instruction.LD, Params.A, Params.BC, 8),
            new InstructionInfo(0x0B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0E, Instruction.LD, Params.C, Params.N, 8),
            new InstructionInfo(0x0F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x10, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x11, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x12, Instruction.LD, Params.DE, Params.A, 8),
            new InstructionInfo(0x13, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x14, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x15, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x16, Instruction.LD, Params.D, Params.N, 8),
            new InstructionInfo(0x17, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x18, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x19, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1A, Instruction.LD, Params.A, Params.DE, 8),
            new InstructionInfo(0x1B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1E, Instruction.LD, Params.E, Params.N, 8),
            new InstructionInfo(0x1F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x20, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x21, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x22, Instruction.LDI, Params.HL, Params.A, 8),
            new InstructionInfo(0x23, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x24, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x25, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x26, Instruction.LD, Params.H, Params.N, 8),
            new InstructionInfo(0x27, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x28, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x29, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2A, Instruction.LDI, Params.A, Params.HL, 8),
            new InstructionInfo(0x2B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2E, Instruction.LD, Params.L, Params.N, 8),
            new InstructionInfo(0x2F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x30, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x31, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x32, Instruction.LDD, Params.HL, Params.A, 8),
            new InstructionInfo(0x33, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x34, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x35, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x36, Instruction.LD, Params.HL, Params.N, 12),
            new InstructionInfo(0x37, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x38, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x39, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3A, Instruction.LDD, Params.A, Params.HL, 8),
            new InstructionInfo(0x3B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3E, Instruction.LD, Params.A, Params.N, 8),
            new InstructionInfo(0x3F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x40, Instruction.LD, Params.B, Params.B, 4),
            new InstructionInfo(0x41, Instruction.LD, Params.B, Params.C, 4),
            new InstructionInfo(0x42, Instruction.LD, Params.B, Params.D, 4),
            new InstructionInfo(0x43, Instruction.LD, Params.B, Params.E, 4),
            new InstructionInfo(0x44, Instruction.LD, Params.B, Params.H, 4),
            new InstructionInfo(0x45, Instruction.LD, Params.B, Params.L, 4),
            new InstructionInfo(0x46, Instruction.LD, Params.B, Params.HL, 8),
            new InstructionInfo(0x47, Instruction.LD, Params.B, Params.A, 4),
            new InstructionInfo(0x48, Instruction.LD, Params.C, Params.B, 4),
            new InstructionInfo(0x49, Instruction.LD, Params.C, Params.C, 4),
            new InstructionInfo(0x4A, Instruction.LD, Params.C, Params.D, 4),
            new InstructionInfo(0x4B, Instruction.LD, Params.C, Params.E, 4),
            new InstructionInfo(0x4C, Instruction.LD, Params.C, Params.H, 4),
            new InstructionInfo(0x4D, Instruction.LD, Params.C, Params.L, 4),
            new InstructionInfo(0x4E, Instruction.LD, Params.C, Params.HL, 8),
            new InstructionInfo(0x4F, Instruction.LD, Params.C, Params.A, 4),
            new InstructionInfo(0x50, Instruction.LD, Params.D, Params.B, 4),
            new InstructionInfo(0x51, Instruction.LD, Params.D, Params.C, 4),
            new InstructionInfo(0x52, Instruction.LD, Params.D, Params.D, 4),
            new InstructionInfo(0x53, Instruction.LD, Params.D, Params.E, 4),
            new InstructionInfo(0x54, Instruction.LD, Params.D, Params.H, 4),
            new InstructionInfo(0x55, Instruction.LD, Params.D, Params.L, 4),
            new InstructionInfo(0x56, Instruction.LD, Params.D, Params.HL, 8),
            new InstructionInfo(0x57, Instruction.LD, Params.D, Params.A, 4),
            new InstructionInfo(0x58, Instruction.LD, Params.E, Params.B, 4),
            new InstructionInfo(0x59, Instruction.LD, Params.E, Params.C, 4),
            new InstructionInfo(0x5A, Instruction.LD, Params.E, Params.D, 4),
            new InstructionInfo(0x5B, Instruction.LD, Params.E, Params.E, 4),
            new InstructionInfo(0x5C, Instruction.LD, Params.E, Params.H, 4),
            new InstructionInfo(0x5D, Instruction.LD, Params.E, Params.L, 4),
            new InstructionInfo(0x5E, Instruction.LD, Params.E, Params.HL, 8),
            new InstructionInfo(0x5F, Instruction.LD, Params.E, Params.A, 4),
            new InstructionInfo(0x60, Instruction.LD, Params.H, Params.B, 4),
            new InstructionInfo(0x61, Instruction.LD, Params.H, Params.C, 4),
            new InstructionInfo(0x62, Instruction.LD, Params.H, Params.D, 4),
            new InstructionInfo(0x63, Instruction.LD, Params.H, Params.E, 4),
            new InstructionInfo(0x64, Instruction.LD, Params.H, Params.H, 4),
            new InstructionInfo(0x65, Instruction.LD, Params.H, Params.L, 4),
            new InstructionInfo(0x66, Instruction.LD, Params.H, Params.HL, 8),
            new InstructionInfo(0x67, Instruction.LD, Params.H, Params.A, 4),
            new InstructionInfo(0x68, Instruction.LD, Params.L, Params.B, 4),
            new InstructionInfo(0x69, Instruction.LD, Params.L, Params.C, 4),
            new InstructionInfo(0x6A, Instruction.LD, Params.L, Params.D, 4),
            new InstructionInfo(0x6B, Instruction.LD, Params.L, Params.E, 4),
            new InstructionInfo(0x6C, Instruction.LD, Params.L, Params.H, 4),
            new InstructionInfo(0x6D, Instruction.LD, Params.L, Params.L, 4),
            new InstructionInfo(0x6E, Instruction.LD, Params.L, Params.HL, 8),
            new InstructionInfo(0x6F, Instruction.ILL, Params.L, Params.A, 4),
            new InstructionInfo(0x70, Instruction.LD, Params.HL, Params.B, 8),
            new InstructionInfo(0x71, Instruction.LD, Params.HL, Params.C, 8),
            new InstructionInfo(0x72, Instruction.LD, Params.HL, Params.D, 8),
            new InstructionInfo(0x73, Instruction.LD, Params.HL, Params.E, 8),
            new InstructionInfo(0x74, Instruction.LD, Params.HL, Params.H, 8),
            new InstructionInfo(0x75, Instruction.LD, Params.HL, Params.L, 8),
            new InstructionInfo(0x76, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x77, Instruction.LD, Params.HL, Params.A, 8),
            new InstructionInfo(0x78, Instruction.LD, Params.A, Params.B, 4),
            new InstructionInfo(0x79, Instruction.LD, Params.A, Params.C, 4),
            new InstructionInfo(0x7A, Instruction.LD, Params.A, Params.D, 4),
            new InstructionInfo(0x7B, Instruction.LD, Params.A, Params.E, 4),
            new InstructionInfo(0x7C, Instruction.LD, Params.A, Params.H, 4),
            new InstructionInfo(0x7D, Instruction.LD, Params.A, Params.L, 4),
            new InstructionInfo(0x7E, Instruction.LD, Params.A, Params.HL, 8),
            new InstructionInfo(0x7F, Instruction.LD, Params.A, Params.A, 4),
            new InstructionInfo(0x80, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x81, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x82, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x83, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x84, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x85, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x86, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x87, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x88, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x89, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x90, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x91, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x92, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x93, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x94, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x95, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x96, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x97, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x98, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x99, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC3, Instruction.JP, Params.NN, Params.NONE, 12),
            new InstructionInfo(0xC4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE2, Instruction.LD, Params.INDEXED_C, Params.A, 8),
            new InstructionInfo(0xE3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE9, Instruction.JP, Params.NONE, Params.HL, 4),
            new InstructionInfo(0xEA, Instruction.LD, Params.NN, Params.A, 16),
            new InstructionInfo(0xEB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xED, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF2, Instruction.LD, Params.A, Params.INDEXED_C, 8),
            new InstructionInfo(0xF3, Instruction.DI, Params.NONE, Params.NONE, 4),
            new InstructionInfo(0xF4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFA, Instruction.LD, Params.A, Params.NN, 16),
            new InstructionInfo(0xFB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFF, Instruction.ILL, Params.NONE, Params.NONE, 1),
    };

    private final static InstructionInfo[] prefixedInstArr = {
            new InstructionInfo(0x00, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x01, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x02, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x03, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x04, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x05, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x06, Instruction.LD, Params.B, Params.N, 8),
            new InstructionInfo(0x07, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x08, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x09, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x0F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x10, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x11, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x12, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x13, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x14, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x15, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x16, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x17, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x18, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x19, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x1F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x20, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x21, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x22, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x23, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x24, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x25, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x26, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x27, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x28, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x29, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x2F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x30, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x31, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x32, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x33, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x34, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x35, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x36, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x37, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x38, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x39, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x3F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x40, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x41, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x42, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x43, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x44, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x45, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x46, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x47, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x48, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x49, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x4A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x4B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x4C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x4D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x4E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x4F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x50, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x51, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x52, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x53, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x54, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x55, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x56, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x57, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x58, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x59, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x5A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x5B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x5C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x5D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x5E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x5F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x60, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x61, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x62, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x63, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x64, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x65, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x66, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x67, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x68, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x69, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x6A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x6B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x6C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x6D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x6E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x6F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x70, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x71, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x72, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x73, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x74, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x75, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x76, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x77, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x78, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x79, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x7A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x7B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x7C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x7D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x7E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x7F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x80, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x81, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x82, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x83, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x84, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x85, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x86, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x87, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x88, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x89, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x8F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x90, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x91, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x92, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x93, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x94, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x95, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x96, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x97, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x98, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x99, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0x9F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xA9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xAF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xB9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xBF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xC9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xCF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xD9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xDF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xE9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xED, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xEF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xF9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo(0xFF, Instruction.ILL, Params.NONE, Params.NONE, 1),
    };

    @Override
    public String toString() {
        final var inst = this.instruction.toString();
        final var to = switch (this.to) {
            case IN_A, IN_B, IN_C, IN_D, IN_E, IN_H, IN_L, BC, DE, HL, NN -> "(" + this.to + ")";
            case NONE ->  "";
            default -> this.to;
        };
        final var from = switch (this.from) {
            case IN_A, IN_B, IN_C, IN_D, IN_E, IN_H, IN_L, BC, DE, HL, NN -> ", (" + this.from + ")";
            case NONE ->  "";
            default -> ", " + this.from;
        };
        return String.format("(0x%02X) %s %s %s", op, inst, to, from);
    }

    public static InstructionInfo getInstruction(int op) {
        return InstructionInfo.instArr[op];
    }

    public static InstructionInfo getCBPrefixedInstruction(int op) {
        return InstructionInfo.prefixedInstArr[op];
    }
}