package devices;

enum Params {
    A,
    IN_A, // (A) register-indirect addressing
    B,
    IN_B, // (B)
    C,
    IN_C, // (C)
    D,
    IN_D, // (D)
    H,
    IN_H, // (H)
    L,
    IN_L, // (L)
    NN,   //  immediate absolute address 2byte
    N,    //  immediate value 1byte
    SP,   //  stack pointer
    NONE,
}

enum Instruction {
    LD,
    PUSH,
    POP,
    ADD,
    ADC,
    SUB,
    SBC,
    AND,
    XOR,
    OR,
    CP,
    INC,
    DEC,
    DAA,
    CPL,
    RLCA,
    RLA,
    RRCA,
    RRA,
    RLC,
    RL,
    RRC,
    RR,
    SLA,
    SWAP,
    SRA,
    SRL,
    BIT,
    SET,
    RES,
    CCF,
    SCF,
    NOP,
    HALT,
    STOP,
    DI,
    EI,
    JP,
    JR,
    CALL,
    RET,
    RETI,
    RST,
    ILL, // Illegal
}

public final class InstructionInfo {
    private final byte op;
    private final Instruction instruction;
    private final Params to;
    private final Params from;
    private final int cycle;

    private InstructionInfo[] instArr = {
            new InstructionInfo((byte) 0x00, Instruction.NOP, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x01, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x02, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x03, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x04, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x05, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x06, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x07, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x08, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x09, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x10, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x11, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x12, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x13, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x14, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x15, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x16, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x17, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x18, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x19, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x20, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x21, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x22, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x23, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x24, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x25, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x26, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x27, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x28, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x29, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x30, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x31, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x32, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x33, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x34, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x35, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x36, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x37, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x38, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x39, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x40, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x41, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x42, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x43, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x44, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x45, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x46, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x47, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x48, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x49, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x50, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x51, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x52, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x53, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x54, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x55, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x56, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x57, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x58, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x59, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x60, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x61, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x62, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x63, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x64, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x65, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x66, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x67, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x68, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x69, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x70, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x71, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x72, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x73, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x74, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x75, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x76, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x77, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x78, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x79, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x80, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x81, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x82, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x83, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x84, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x85, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x86, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x87, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x88, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x89, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x90, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x91, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x92, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x93, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x94, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x95, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x96, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x97, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x98, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x99, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xED, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFF, Instruction.ILL, Params.NONE, Params.NONE, 1),
    };

    private InstructionInfo[] prefixedInstArr = {
            new InstructionInfo((byte) 0x00, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x01, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x02, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x03, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x04, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x05, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x06, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x07, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x08, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x09, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x0F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x10, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x11, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x12, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x13, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x14, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x15, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x16, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x17, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x18, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x19, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x1F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x20, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x21, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x22, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x23, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x24, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x25, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x26, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x27, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x28, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x29, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x2F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x30, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x31, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x32, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x33, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x34, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x35, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x36, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x37, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x38, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x39, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x3F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x40, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x41, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x42, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x43, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x44, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x45, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x46, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x47, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x48, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x49, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x4F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x50, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x51, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x52, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x53, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x54, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x55, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x56, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x57, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x58, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x59, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x5F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x60, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x61, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x62, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x63, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x64, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x65, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x66, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x67, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x68, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x69, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x6F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x70, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x71, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x72, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x73, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x74, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x75, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x76, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x77, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x78, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x79, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x7F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x80, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x81, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x82, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x83, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x84, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x85, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x86, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x87, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x88, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x89, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x8F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x90, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x91, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x92, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x93, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x94, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x95, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x96, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x97, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x98, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x99, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9A, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9B, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9C, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9D, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9E, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0x9F, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xA9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xAF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xB9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xBF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xC9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xCF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xD9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xDF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xE9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xED, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xEF, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF0, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF1, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF2, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF3, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF4, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF5, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF6, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF7, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF8, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xF9, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFA, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFB, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFC, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFD, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFE, Instruction.ILL, Params.NONE, Params.NONE, 1),
            new InstructionInfo((byte) 0xFF, Instruction.ILL, Params.NONE, Params.NONE, 1),
    };

    private InstructionInfo(final byte op, final Instruction instruction, final Params to, final Params from, final int cycle) {
        this.op = op;
        this.instruction = instruction;
        this.to = to;
        this.from = from;
        this.cycle = cycle;
    }

    public static InstructionInfo getInstruction(byte op) {
        return null;
    }

    public static InstructionInfo getCBPrefixedInstruction() {
        return null;
    }
}